#+title: Challenge
#+subtitle: AutosRUS Analysis
#+author: Alberto Valdez
#+SETUPFILE: ./config/org-theme-alt.config
#+SETUPFILE: ./config/org-header.config
#+PROPERTY: header-args:R :session "inferior ESS" :results value table :colnames yes :wrap org :width 960 :height 640 :res 144
#+OPTIONS: ^:nil
#+OPTIONS: \n:t

* Part 1: Predict MPG

#+NAME: import-1
#+begin_src R :results silent
library(dplyr)
library(ggplot2)
library(tidyverse)
#+end_src

#+NAME: w5
#+begin_src elisp :var data="" :wrap org
(concat "#+attr_html: :width 500px\n" data "")
#+end_src

** Import Data

#+NAME: load-1
#+begin_src R
mpgcar <-
  read.csv(
    'MechaCar_mpg.csv',
    check.names = F,
    stringsAsFactors = F
)
head(mpgcar)
#+end_src

#+RESULTS[b93a2a902e8ca4c3c3cd63466a9a1a8292bf2f26]: load-1
#+begin_org
| vehicle_length | vehicle_weight | spoiler_angle | ground_clearance | AWD |         mpg |
|----------------+----------------+---------------+------------------+-----+-------------|
|    14.69709536 |     6407.94647 |   48.78998258 |      14.64098303 |   1 | 49.04918045 |
|    12.53420597 |    5182.080571 |            90 |      14.36667939 |   1 | 36.76606309 |
|             20 |    8337.981208 |   78.63232282 |      12.25371141 |   0 |          80 |
|    13.42848546 |    9419.670939 |   55.93903153 |      12.98935921 |   1 |  18.9414895 |
|    15.44997974 |    3772.666826 |   26.12816424 |      15.10396274 |   1 | 63.82456769 |
|    14.45356979 |    7286.594508 |   30.58567612 |      13.10695343 |   0 | 48.54267684 |
#+end_org

** Linear regression

#+NAME: lr-1
#+begin_src R :results output
lm(
  mpg ~ vehicle_length +
  vehicle_weight +
  spoiler_angle +
  ground_clearance +
  AWD,
  data = mpgcar
)
#+end_src

#+RESULTS[b1553930ccf2bea6e36ee35b27dbaa7e5f08398a]: lr-1
#+begin_org

Call:
lm(formula = mpg ~ vehicle_length + vehicle_weight + spoiler_angle +
    ground_clearance + AWD, data = mpgcar)

Coefficients:
     (Intercept)    vehicle_length    vehicle_weight     spoiler_angle
      -1.040e+02         6.267e+00         1.245e-03         6.877e-02
ground_clearance               AWD
       3.546e+00        -3.411e+00
#+end_org

#+NAME: summary-1
#+begin_src R :results output
summary(
  lm(
    mpg ~ vehicle_length +
    vehicle_weight +
    spoiler_angle +
    ground_clearance +
    AWD,
    data = mpgcar
  )
)
#+end_src

#+RESULTS[31375ea670c70eb40478a2b473955b010318e6fe]: summary-1
#+begin_org

Call:
lm(formula = mpg ~ vehicle_length + vehicle_weight + spoiler_angle +
    ground_clearance + AWD, data = mpgcar)

Residuals:
     Min       1Q   Median       3Q      Max
-19.4701  -4.4994  -0.0692   5.4433  18.5849

Coefficients:
                   Estimate Std. Error t value Pr(>|t|)
(Intercept)      -1.040e+02  1.585e+01  -6.559 5.08e-08 ***
vehicle_length    6.267e+00  6.553e-01   9.563 2.60e-12 ***
vehicle_weight    1.245e-03  6.890e-04   1.807   0.0776 .
spoiler_angle     6.877e-02  6.653e-02   1.034   0.3069
ground_clearance  3.546e+00  5.412e-01   6.551 5.21e-08 ***
AWD              -3.411e+00  2.535e+00  -1.346   0.1852
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 8.774 on 44 degrees of freedom
Multiple R-squared:  0.7149,	Adjusted R-squared:  0.6825
F-statistic: 22.07 on 5 and 44 DF,  p-value: 5.35e-11
#+end_org

* Part 2: Trip Analysis Visualization

#+NAME: load-2
#+begin_src R
coildata <-
   read.csv(
    'Suspension_Coil.csv',
    check.names = F,
    stringsAsFactors = F
)
head(coildata)
#+end_src

#+RESULTS[50f5e0286fcc1a7c4d10c242a2099c61e102a332]: load-2
#+begin_org
| VehicleID | Manufacturing_Lot |  PSI |
|-----------+-------------------+------|
| V40858    | Lot1              | 1499 |
| V40607    | Lot1              | 1500 |
| V31443    | Lot1              | 1500 |
| V6004     | Lot1              | 1500 |
| V7000     | Lot1              | 1501 |
| V17344    | Lot1              | 1501 |
#+end_org

Write an RScript that creates a total_summary dataframe using the summarize() function to get the mean, median, variance, and standard deviation of the suspension coil’s PSI column.

#+NAME: summary-2
#+begin_src R
total_summary <-
  coildata %>%
  summarize(
    Mean=mean(PSI),
    Median=median(PSI),
    Variance=var(PSI),
    SD=sd(PSI)
)
#+end_src

#+RESULTS[4b03a0f1d518fa333d7c38a1ffedeea8fc327401]: summary-2
#+begin_org
|    Mean | Median |         Variance |               SD |
|---------+--------+------------------+------------------|
| 1498.78 |   1500 | 62.2935570469799 | 7.89262675203762 |
#+end_org

#+NAME: summary-2b
#+begin_src R
lot_summary <-
  coildata %>%
  group_by(Manufacturing_Lot) %>%
  summarize(
    Mean=mean(PSI),
    Median=median(PSI),
    Variance=var(PSI),
    SD=sd(PSI),
    .groups='keep'
  )
#+end_src

#+RESULTS[1a03438201e63e1cfd48daeadc236c06b8e61424]: summary-2b
#+begin_org
| Manufacturing_Lot |    Mean | Median |          Variance |                SD |
|-------------------+---------+--------+-------------------+-------------------|
| Lot1              |    1500 |   1500 | 0.979591836734694 | 0.989743318610787 |
| Lot2              |  1500.2 |   1500 |  7.46938775510204 |  2.73301806710128 |
| Lot3              | 1496.14 | 1498.5 |   170.28612244898 |  13.0493724925369 |
#+end_org

* Part 3: T-Tests on Suspension Coils

In your MechaCarChallenge.RScript, write an RScript using the t.test() function to determine if the PSI across all manufacturing lots is statistically different from the population mean of 1,500 pounds per square inch.

#+NAME: test-1
#+begin_src R :results output
t.test(
  coildata$PSI,
  mu=mean(coildata$PSI)
)
#+end_src

#+RESULTS[8295c9198c0bfe52eea918515aace9cbd8489f09]: test-1
#+begin_org

	One Sample t-test

data:  coildata$PSI
t = 0, df = 149, p-value = 1
alternative hypothesis: true mean is not equal to 1498.78
95 percent confidence interval:
 1497.507 1500.053
sample estimates:
mean of x
  1498.78
#+end_org

Next, write three more RScripts in your MechaCarChallenge.RScript using the t.test() function and its subset() argument to determine if the PSI for each manufacturing lot is statistically different from the population mean of 1,500 pounds per square inch.

#+NAME: test-2a
#+begin_src R :results output
t.test(
  subset(
    coildata$PSI,
    coildata$Manufacturing_Lot == "Lot1"
  ),
  mu=mean(coildata$PSI)
)
#+end_src

#+RESULTS[01f2e150b9ab2ee98c6a99443bda93fbb66823d4]: test-2a
#+begin_org

	One Sample t-test

data:  subset(coildata$PSI, coildata$Manufacturing_Lot == "Lot1")
t = 8.7161, df = 49, p-value = 1.568e-11
alternative hypothesis: true mean is not equal to 1498.78
95 percent confidence interval:
 1499.719 1500.281
sample estimates:
mean of x
     1500
#+end_org

#+NAME: test-2b
#+begin_src R :results output
t.test(
  subset(
    coildata$PSI,
    coildata$Manufacturing_Lot == "Lot2"
  ),
  mu=mean(coildata$PSI)
)
#+end_src

#+RESULTS[96ce308ac0d856c470640c780a9f64a9f86c06b7]: test-2b
#+begin_org

	One Sample t-test

data:  subset(coildata$PSI, coildata$Manufacturing_Lot == "Lot2")
t = 3.6739, df = 49, p-value = 0.0005911
alternative hypothesis: true mean is not equal to 1498.78
95 percent confidence interval:
 1499.423 1500.977
sample estimates:
mean of x
   1500.2
#+end_org

#+NAME: test-2c
#+begin_src R :results output
t.test(
  subset(
    coildata$PSI,
    coildata$Manufacturing_Lot == "Lot3"
  ),
  mu=mean(coildata$PSI)
)
#+end_src

#+RESULTS[f31749f33db386ae4788dd6288cb5924909d8730]: test-2c
#+begin_org

	One Sample t-test

data:  subset(coildata$PSI, coildata$Manufacturing_Lot == "Lot3")
t = -1.4305, df = 49, p-value = 0.1589
alternative hypothesis: true mean is not equal to 1498.78
95 percent confidence interval:
 1492.431 1499.849
sample estimates:
mean of x
  1496.14
#+end_org

* Complete script

Complete code for MechaCharChallenge.

#+NAME: rscript
#+begin_src R :eval no :tangle MechaCarChallenge.R
<<import-1>>
<<load-1>>
<<lr-1>>
<<summary-1>>
<<load-2>>
<<summary-2>>
<<summary-2b>>
<<test-1>>
<<test-2a>>
<<test-2b>>
<<test-2c>>
#+end_src

#+NAME: rscript2
#+begin_src R :eval no :tangle :exports none MechaCarChallenge.RScript
<<rscript>>
#+end_src
